# all settings listed here - https://github.com/probot/stale#usage

daysUntilStale: 60
daysUntilClose: 1
exemptAssignees: true
# use this property to disable stale bot when we apply the wontfix label, prevents users from playing stale bot ping pong and keeping an issue open with no intent of action
exemptLabels:
  - status:wontfix
  - status:hold
only: issues
staleLabel: status:stale
markComment: false
closeComment: >
  Hey folks. This issue hasn't received any traction for 60 days, so we're going to close this for housekeeping.
  If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further
  discussion is always welcome even with the issue closed. If anything actionable is posted in the comments,
  we'll consider reopening it.  [ⓘ](https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea)
