name: Validate packages

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  push:
    branches:
      - '*'
      - '!main'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16', '14', '12']

    name: Node v${{ matrix.node }}

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node#v2
      - uses: actions/setup-node@v2

      - name: We need NPM 7.x to support --workflow
        run: sudo npm i -g npm@latest

      - run: npm install

      - name: Lint packages
        run: npm run lint

      - name: Build packages
        run: npm run build

      - name: Tests packages
        run: npm run test
