name: Validation
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  push:
    branches:
      - "*"
      - "!main"

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16.10
          - 14.17
          - 12.22
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # We need NPM >=7 to support --workflow
      - run: npm i -g npm@latest
      - run: npm ci
      - run: npm run lint
      - run: npm run build -w tsmodule
      - run: npm test
